import { ArrowLeftRight, Download, FilePlus2, Play, Square } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";

import { UtilityField, UtilityNotice, UtilityPage, UtilitySectionCard, UtilitySelect } from "../../components/UtilitySurface";
import { FileDropZone, PageHeader, SegmentedControl } from "../../components/ui";
import { Button } from "../../components/ui/button";
import { useAppLanguage } from "../../i18n/routing";
import { PdfCompareSession } from "./session";
import { writeComparisonReports } from "./report";
import type { ComparisonResult, PageComparison, PageMapping, PdfCompareErrorCode, PixelThreshold, SelectedPreview } from "./types";

type DraftPair = { id: string; before: File | null; after: File | null; mapping?: PageMapping[] };
type ViewMode = "side" | "overlay";

const copy = {
  ko: { eyebrow:"PDF 비교", title:"PDF 파일 비교", description:"수정 전후 PDF를 쌍으로 놓고 페이지별 화면과 추출 텍스트 차이를 확인합니다.", files:"PDF 쌍 선택", filesDesc:"각 쌍의 수정 전·후 파일을 선택하세요. 파일은 브라우저 안에서만 처리됩니다.", before:"수정 전 PDF", after:"수정 후 PDF", hint:"PDF 파일 1개", add:"비교 쌍 추가", remove:"쌍 삭제", swap:"좌우 교체", settings:"비교 설정", threshold:"픽셀 민감도", mapping:"쪽 번호로 대응", run:"비교 시작", rerun:"다시 비교", cancel:"비교 취소", running:"페이지를 비교하고 있습니다.", results:"비교 결과", changedOnly:"변경 페이지만 보기", all:"모든 페이지", side:"좌우 보기", overlay:"차이 겹쳐 보기", opacity:"겹침 불투명도", report:"보고서 다운로드", select:"페이지 선택", page:"{{n}}번째 대응", added:"추가", deleted:"삭제", changed:"변경", sameVisual:"렌더 픽셀 차이 없음", sameText:"추출된 텍스트에서 차이 없음", noText:"비교할 텍스트 없음", unknown:"확인되지 않음", canceled:"취소됨", failed:"비교 실패", partial:"완료된 페이지를 포함한 부분 결과입니다.", limit:"추출 텍스트의 읽기 순서와 글자는 PDF 내부 정보에 따라 실제 화면과 다를 수 있습니다. 화면 비교와 텍스트 비교 결과를 각각 확인하세요.", renderLimit:"화면 비교는 같은 렌더 설정의 픽셀 차이이며 문서 내용의 동일성을 뜻하지 않습니다.", reduced:"큰 페이지를 낮은 해상도로 비교했습니다.", size:"페이지 크기 변경", dpi:"실제 {{dpi}} DPI · 배율 {{scale}}", manual:"수동 대응", none:"없음", apply:"대응 적용 후 재실행", needFiles:"각 쌍에 수정 전·후 PDF를 선택하세요.", password:"암호가 없는 PDF 사본을 선택하세요.", invalid:"PDF 파일을 읽을 수 없습니다. 파일이 손상되지 않았는지 확인하세요.", renderError:"페이지 화면을 비교하지 못했습니다.", mappingError:"페이지 대응을 확인하세요. 각 페이지는 한 번만 사용할 수 있습니다.", exportError:"보고서를 만들지 못했습니다. 다시 시도하세요.", empty:"조건에 맞는 페이지가 없습니다." },
  en: { eyebrow:"PDF comparison", title:"Compare PDF files", description:"Place before and after PDFs in pairs, then inspect visual and extracted-text differences page by page.", files:"Choose PDF pairs", filesDesc:"Choose one before and one after file for each pair. Files stay in your browser.", before:"Before PDF", after:"After PDF", hint:"One PDF file", add:"Add comparison pair", remove:"Remove pair", swap:"Swap sides", settings:"Comparison settings", threshold:"Pixel sensitivity", mapping:"Match by page number", run:"Start comparison", rerun:"Compare again", cancel:"Cancel comparison", running:"Comparing pages.", results:"Comparison results", changedOnly:"Changed pages only", all:"All pages", side:"Side by side", overlay:"Difference overlay", opacity:"Overlay opacity", report:"Download report", select:"Select page", page:"Pair {{n}}", added:"Added", deleted:"Deleted", changed:"Changed", sameVisual:"No rendered pixel difference", sameText:"No difference in extracted text", noText:"No text to compare", unknown:"Unknown", canceled:"Canceled", failed:"Comparison failed", partial:"This is a partial result containing completed pages.", limit:"Extracted text order and characters can differ from the visible PDF because they follow the PDF's internal data. Check visual and text results separately.", renderLimit:"Visual comparison reports pixel differences under the same render settings and does not establish document equivalence.", reduced:"A large page was compared at reduced resolution.", size:"Page size changed", dpi:"Actual {{dpi}} DPI · scale {{scale}}", manual:"Manual matching", none:"None", apply:"Apply mapping and compare again", needFiles:"Choose a before and after PDF for every pair.", password:"Choose an unlocked copy of the PDF.", invalid:"The PDF could not be read. Check that the file is not damaged.", renderError:"The page could not be rendered for comparison.", mappingError:"Check the page mapping. Each page can be used only once.", exportError:"The report could not be created. Try again.", empty:"No pages match this filter." }
} as const;

export function PdfComparePage() {
  const language = useAppLanguage(); const c = copy[language];
  const sessionRef = useRef<PdfCompareSession | null>(null); if (!sessionRef.current) sessionRef.current = new PdfCompareSession();
  const [pairs,setPairs]=useState<DraftPair[]>(()=>[{id:crypto.randomUUID(),before:null,after:null}]);
  const [threshold,setThreshold]=useState<PixelThreshold>(16); const [result,setResult]=useState<ComparisonResult|null>(null);
  const [busy,setBusy]=useState(false); const [progress,setProgress]=useState(0); const [error,setError]=useState<string>();
  const [changedOnly,setChangedOnly]=useState(false); const [selected,setSelected]=useState<{pair:number;page:number}|null>(null);
  const [preview,setPreview]=useState<SelectedPreview|null>(null); const [view,setView]=useState<ViewMode>("side"); const [opacity,setOpacity]=useState(.55);
  const exportController=useRef<AbortController | null>(null);
  const generation=useRef(0);
  const exportUrls=useRef(new Map<string,ReturnType<typeof setTimeout>>());
  const cancelExport=()=>{
    exportController.current?.abort(); exportController.current=null;
    for(const [url,timer] of exportUrls.current){clearTimeout(timer);URL.revokeObjectURL(url);}
    exportUrls.current.clear();
  };
  useEffect(()=>()=>{ generation.current++; cancelExport(); void sessionRef.current?.dispose(); },[]);
  const invalidate=()=>{ generation.current++; cancelExport(); sessionRef.current?.invalidate(); setResult(null); setSelected(null); setPreview(null); setError(undefined); setBusy(false); };
  const updatePair=(index:number,patch:Partial<DraftPair>)=>{ invalidate(); setPairs(current=>current.map((pair,i)=>i===index?{...pair,...patch}:pair)); };
  const addPair=()=>{ invalidate(); setPairs(current=>[...current,{id:crypto.randomUUID(),before:null,after:null}]); };
  const inputs=useMemo(()=>pairs.flatMap(pair=>pair.before&&pair.after?[{id:pair.id,before:pair.before,after:pair.after,mapping:pair.mapping}]:[]),[pairs]);
  const run=async()=>{
    if(inputs.length!==pairs.length){setError(c.needFiles);return;}
    invalidate(); const current=generation.current; setBusy(true);setProgress(1);
    try {
      const next=await sessionRef.current!.run(inputs,threshold,p=>{
        if(current===generation.current)setProgress(Math.max(1,Math.round(((p.pairIndex+(p.totalPages?p.completedPages/p.totalPages:0))/p.pairCount)*100)));
      });
      if(next&&current===generation.current){setResult(next);setProgress(100);}
    } catch(e){ if(current===generation.current&&!(e instanceof DOMException&&e.name==="AbortError"))setError(c.invalid); }
    finally {if(current===generation.current)setBusy(false);}
  };
  const cancel=()=>sessionRef.current?.cancel();
  const choose=async(pairIndex:number,pageIndex:number)=>{ setSelected({pair:pairIndex,page:pageIndex});setPreview(null);const page=result?.pairs[pairIndex]?.pages[pageIndex];if(!page)return;try{const next=await sessionRef.current!.select(inputs[pairIndex],page.mapping,threshold);setPreview(next);}catch(e){if(!(e instanceof DOMException&&e.name==="AbortError"))setError(c.renderError);}};
  const download=async()=>{
    if(!result||busy||sessionRef.current?.result!==result)return;
    cancelExport(); const controller=new AbortController();exportController.current=controller;const current=generation.current;
    const isCurrent=()=>!controller.signal.aborted&&exportController.current===controller&&current===generation.current;
    try{
      const out=await writeComparisonReports(result.pairs,language,controller.signal);
      if(!isCurrent())return;
      const url=URL.createObjectURL(out.blob);
      const timer=setTimeout(()=>{URL.revokeObjectURL(url);exportUrls.current.delete(url);},15000);exportUrls.current.set(url,timer);
      const a=document.createElement("a");a.href=url;a.download=out.fileName;a.click();
    }catch(e){if(isCurrent()&&!(e instanceof DOMException&&e.name==="AbortError"))setError(c.exportError);}
    finally{if(exportController.current===controller)exportController.current=null;}
  };
  const selectedPage=selected?result?.pairs[selected.pair]?.pages[selected.page]:undefined;
  return <UtilityPage toolId="pdf-compare">
    <PageHeader eyebrow={c.eyebrow} title={c.title} description={c.description}/>
    <UtilityNotice className="mb-4" tone="warning">{c.limit}</UtilityNotice>
    <UtilitySectionCard title={c.files} description={c.filesDesc} step={1}>
      <div className="space-y-4">{pairs.map((pair,index)=><div className="rounded-3xl border border-border p-4" key={pair.id} data-testid="pdf-pair">
        <div className="mb-3 flex flex-wrap items-center justify-between gap-2"><strong>{c.page.replace("{{n}}",String(index+1))}</strong><div className="flex gap-2"><Button type="button" variant="outline" className="min-h-11" onClick={()=>updatePair(index,{before:pair.after,after:pair.before,mapping:undefined})}><ArrowLeftRight size={16}/>{c.swap}</Button>{pairs.length>1?<Button type="button" variant="ghost" className="min-h-11" onClick={()=>{invalidate();setPairs(current=>current.filter((_,i)=>i!==index));}}>{c.remove}</Button>:null}</div></div>
        <div className="grid gap-4 min-[1000px]:grid-cols-2"><FileDropZone label={c.before} hint={c.hint} accept="application/pdf,.pdf" files={pair.before?[pair.before]:[]} onFiles={files=>updatePair(index,{before:files[0]??null,mapping:undefined})} accent="violet" disabled={busy}/><FileDropZone label={c.after} hint={c.hint} accept="application/pdf,.pdf" files={pair.after?[pair.after]:[]} onFiles={files=>updatePair(index,{after:files[0]??null,mapping:undefined})} accent="violet" disabled={busy}/></div>
      </div>)}</div>
      <Button type="button" variant="outline" className="mt-4 min-h-11" disabled={busy} onClick={addPair}><FilePlus2 size={17}/>{c.add}</Button>
    </UtilitySectionCard>
    <UtilitySectionCard title={c.settings} step={2}><div className="grid gap-4 min-[621px]:grid-cols-2"><UtilityField>{c.threshold}<UtilitySelect value={threshold} disabled={busy} onChange={e=>{invalidate();setThreshold(Number(e.target.value) as PixelThreshold)}}><option value="0">0</option><option value="16">16</option><option value="32">32</option></UtilitySelect></UtilityField><UtilityField>{c.mapping}<div className="flex h-10 items-center rounded-xl border border-input px-3 text-sm">{c.mapping}</div></UtilityField></div><div className="mt-5 flex gap-3">{busy?<Button className="min-h-12 flex-1" variant="destructive" onClick={cancel}><Square size={17}/>{c.cancel}</Button>:<Button className="min-h-12 flex-1" onClick={()=>void run()}><Play size={17}/>{result?c.rerun:c.run}</Button>}</div>{busy?<div className="mt-4" role="status" aria-live="polite"><div className="mb-1 flex justify-between text-sm"><span>{c.running}</span><b>{progress}%</b></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-violet-700" style={{width:`${progress}%`}}/></div></div>:null}{error?<UtilityNotice className="mt-4" tone="error" role="alert">{error}</UtilityNotice>:null}</UtilitySectionCard>
    {result?<UtilitySectionCard title={c.results} step={3}><div className="mb-4 flex flex-wrap gap-3"><SegmentedControl value={changedOnly?"changed":"all"} label={c.changedOnly} options={[{value:"all",label:c.all},{value:"changed",label:c.changedOnly}]} onChange={v=>setChangedOnly(v==="changed")}/><Button type="button" className="min-h-11" onClick={()=>void download()}><Download size={17}/>{c.report}</Button></div>{result.canceled?<UtilityNotice tone="warning">{c.partial}</UtilityNotice>:null}<div className="mb-5 space-y-3">{result.pairs.map((pair,pi)=>pair.status==="failed"?null:<MappingEditor key={pair.id} pair={pair} c={c} onApply={mapping=>updatePair(pi,{mapping})}/>)}</div><div className="mt-4 grid gap-5 min-[821px]:grid-cols-[280px_minmax(0,1fr)]"><nav className="max-h-[620px] space-y-3 overflow-auto" aria-label={c.select}>{result.pairs.map((pair,pi)=><div key={pair.id}><strong className="mb-2 block truncate">{pair.beforeName} ↔ {pair.afterName}</strong>{pair.status==="failed"?<UtilityNotice tone="error">{errorText(pair.error,c)}</UtilityNotice>:pair.pages.map((page,pg)=>{const changed=isChanged(page);if(changedOnly&&!changed)return null;return <Button key={pg} type="button" variant={selected?.pair===pi&&selected.page===pg?"default":"outline"} className="mb-2 h-auto min-h-11 w-full justify-start whitespace-normal text-left" onClick={()=>void choose(pi,pg)}>{mappingLabel(page.mapping)} · {statusText(page,c)}</Button>})}</div>)}</nav><div>{selectedPage?<><div className="mb-3 flex flex-wrap gap-3"><SegmentedControl value={view} label={c.select} options={[{value:"side",label:c.side},{value:"overlay",label:c.overlay}]} onChange={setView}/>{view==="overlay"?<UtilityField className="min-w-48">{c.opacity}<input type="range" min="0" max="1" step=".05" value={opacity} onChange={e=>setOpacity(Number(e.target.value))}/></UtilityField>:null}</div><Preview preview={preview} view={view} opacity={opacity}/><PageDetails page={selectedPage} c={c}/></>:<p className="rounded-3xl border border-dashed p-8 text-center text-muted-foreground">{c.select}</p>}</div></div></UtilitySectionCard>:null}
    <UtilityNotice tone="warning">{c.renderLimit} {language === "ko" ? "시각 비교는 현재 브라우저의 표시 결과를 비교합니다. 화면 배율, 기기와 글꼴 환경에 따라 차이율이 달라질 수 있습니다." : "Visual comparison uses the rendering in your current browser. Pixel differences can vary with display scaling, devices and available fonts."}</UtilityNotice>
  </UtilityPage>;
}

function Preview({preview,view,opacity}:{preview:SelectedPreview|null;view:ViewMode;opacity:number}){if(!preview)return <div className="min-h-48 animate-pulse rounded-3xl bg-muted" role="status"/>;return <div className={view==="side"?"grid gap-3 sm:grid-cols-2":"relative mx-auto w-fit max-w-full overflow-auto rounded-2xl border bg-white"}>{view==="side"?<><CanvasHost canvas={preview.before}/><CanvasHost canvas={preview.after}/></>:<><CanvasHost canvas={preview.before}/><div className="pointer-events-none absolute inset-0" style={{opacity}}><CanvasHost canvas={preview.overlay}/></div></>}</div>}
function CanvasHost({canvas}:{canvas:HTMLCanvasElement|null}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const host=ref.current;if(canvas&&host){host.replaceChildren(canvas);canvas.style.maxWidth="100%";canvas.style.height="auto";}return()=>{if(host&&canvas?.parentElement===host)host.removeChild(canvas)}},[canvas]);return <div ref={ref} className="min-w-0 overflow-auto rounded-2xl border bg-white"/>}
function PageDetails({page,c}:{page:PageComparison;c:(typeof copy)["ko"]|(typeof copy)["en"]}){return <div className="mt-4 space-y-3"><div className="flex flex-wrap gap-2 text-sm"><span className="rounded-full bg-muted px-3 py-1">{statusText(page,c)}</span>{page.geometry?.pageSizeChanged?<span className="rounded-full bg-amber-500/10 px-3 py-1 text-amber-800 dark:text-amber-300">{c.size}</span>:null}{page.geometry?<span className="rounded-full bg-muted px-3 py-1">{c.dpi.replace("{{dpi}}",String(Math.round(page.geometry.dpi))).replace("{{scale}}",page.geometry.scaleFactor.toFixed(2))}</span>:null}</div>{page.geometry?.reducedResolution?<UtilityNotice tone="warning">{c.reduced}</UtilityNotice>:null}<div className="grid gap-3 sm:grid-cols-2"><TextPanel title={c.before} text={page.beforeText} available={page.beforeTextAvailable} c={c}/><TextPanel title={c.after} text={page.afterText} available={page.afterTextAvailable} c={c}/></div>{page.textComparison==="different-extracted-text"?<div className="rounded-2xl border p-4 whitespace-pre-wrap">{page.segments.map((s,i)=><span key={i} className={s.type==="added"?"bg-green-200 text-green-950 dark:bg-green-900 dark:text-green-100":s.type==="deleted"?"bg-red-200 text-red-950 line-through dark:bg-red-900 dark:text-red-100":""}>{s.text}</span>)}</div>:null}</div>}
function TextPanel({title,text,available,c}:{title:string;text:string;available:boolean;c:(typeof copy)["ko"]|(typeof copy)["en"]}){return <section className="min-w-0 rounded-2xl border p-4"><strong>{title}</strong><pre className="mt-2 max-h-64 overflow-auto whitespace-pre-wrap break-words text-sm">{available?text:c.noText}</pre></section>}
function MappingEditor({pair,c,onApply}:{pair:ComparisonResult["pairs"][number];c:(typeof copy)["ko"]|(typeof copy)["en"];onApply:(mapping:PageMapping[])=>void}){const [open,setOpen]=useState(false);const [rows,setRows]=useState<PageMapping[]>(()=>pair.pages.map(page=>({...page.mapping})));const duplicate=hasDuplicate(rows,"before")||hasDuplicate(rows,"after")||rows.some(row=>row.before===null&&row.after===null);return <section className="rounded-2xl border p-3"><Button type="button" variant="ghost" className="min-h-11 w-full justify-between" aria-expanded={open} onClick={()=>setOpen(value=>!value)}><span className="truncate">{pair.beforeName} ↔ {pair.afterName}</span><span>{c.manual}</span></Button>{open?<div className="mt-3 space-y-2">{rows.map((row,index)=><div className="grid grid-cols-[1fr_auto_1fr] items-center gap-2" key={index}><PageSelect label={c.before} count={pair.beforePageCount} value={row.before} none={c.none} onChange={before=>setRows(current=>current.map((item,i)=>i===index?{...item,before}:item))}/><span aria-hidden="true">↔</span><PageSelect label={c.after} count={pair.afterPageCount} value={row.after} none={c.none} onChange={after=>setRows(current=>current.map((item,i)=>i===index?{...item,after}:item))}/></div>)}{duplicate?<UtilityNotice tone="error">{c.mappingError}</UtilityNotice>:null}<Button type="button" className="min-h-11 w-full" disabled={duplicate} onClick={()=>onApply(rows)}>{c.apply}</Button></div>:null}</section>}
function PageSelect({label,count,value,none,onChange}:{label:string;count:number;value:number|null;none:string;onChange:(value:number|null)=>void}){return <UtilitySelect aria-label={label} value={value===null?"":String(value)} onChange={event=>onChange(event.target.value===""?null:Number(event.target.value))}><option value="">{none}</option>{Array.from({length:count},(_,index)=><option value={index} key={index}>{index+1}</option>)}</UtilitySelect>}
function hasDuplicate(rows:PageMapping[],side:keyof PageMapping){const values=rows.map(row=>row[side]).filter((value):value is number=>value!==null);return new Set(values).size!==values.length}
function isChanged(page:PageComparison){return page.status!=="complete"||page.visualComparison!=="equal-pixels"||page.textComparison!=="equal-extracted-text"||Boolean(page.geometry?.pageSizeChanged)}
function mappingLabel(m:PageMapping){return `${m.before===null?"—":m.before+1} ↔ ${m.after===null?"—":m.after+1}`}
function statusText(page:PageComparison,c:(typeof copy)["ko"]|(typeof copy)["en"]){if(page.status==="canceled")return c.canceled;if(page.status!=="complete")return c.unknown;if(page.visualComparison==="added")return c.added;if(page.visualComparison==="deleted")return c.deleted;if(page.textComparison==="unavailable")return page.visualComparison==="equal-pixels"?`${c.sameVisual} · ${c.noText}`:c.changed;if(isChanged(page))return c.changed;return `${c.sameVisual} · ${c.sameText}`}
function errorText(code:PdfCompareErrorCode|undefined,c:(typeof copy)["ko"]|(typeof copy)["en"]){return code==="password"?c.password:code==="invalid-mapping"?c.mappingError:code==="render-failed"?c.renderError:c.invalid}
