import fs from'node:fs/promises';import assert from'node:assert/strict';import{chromium}from'playwright';
const base=process.env.REDACTOR_BASE_URL??'http://127.0.0.1:4330';const output=process.env.REDACTOR_OUTPUT??'/tmp/worklazy-u6-preflight/p1-engine/network';await fs.mkdir(output,{recursive:true});
const input=Array.from(await fs.readFile(process.env.REDACTOR_FIXTURES?process.env.REDACTOR_FIXTURES+'/three-pages.pdf':'/tmp/worklazy-u6-preflight/p1-engine/fixtures/three-pages.pdf'));const png=Array.from(await fs.readFile(process.env.REDACTOR_FIXTURES?process.env.REDACTOR_FIXTURES+'/palette-alpha.png':'/tmp/worklazy-u6-preflight/p1-engine/fixtures/palette-alpha.png'));
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',args:['--no-sandbox']});const rows=[];
for(const mutant of [false,true]){
const context=await browser.newContext({serviceWorkers:'block'});const contextRequests=[],workers=[],websockets=[],errors=[];let marker;const requests=new Map();
const requestObjects=new Map();context.on('request',r=>{const entry={url:r.url(),at:Date.now()};contextRequests.push(entry);requestObjects.set(r,entry);});for(const event of ['requestfinished','requestfailed'])context.on(event,r=>{const entry=requestObjects.get(r);if(entry){entry.timing=r.timing();entry.terminal=event;entry.eventAt=Date.now();}});await context.route('**/*',r=>{const url=r.request().url();return url.includes('/p0-enable-window-negative')||new URL(url).origin!==base?r.abort():r.continue();});
await context.addInitScript(({mutant})=>{
window.__p0Csp=[];document.addEventListener('securitypolicyviolation',e=>window.__p0Csp.push({at:performance.timeOrigin+performance.now(),blocked:e.blockedURI,directive:e.effectiveDirective}));
const descriptor=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'disabled');
Object.defineProperty(HTMLInputElement.prototype,'disabled',{...descriptor,set(value){descriptor.set.call(this,value);if(this.id==='input'&&value===false){const at=performance.timeOrigin+performance.now();window.__p0EnabledAt=at;console.debug('__P0_INPUT_ENABLE__',at);if(mutant)fetch('/p0-enable-window-negative').catch(()=>{});}}});
},{mutant});
const page=await context.newPage();page.on('worker',w=>workers.push(w.url()));page.on('pageerror',e=>errors.push(String(e)));const cdp=await context.newCDPSession(page);await cdp.send('Network.enable');await cdp.send('Runtime.enable');
cdp.on('Runtime.consoleAPICalled',e=>{if(e.args[0]?.value==='__P0_INPUT_ENABLE__')marker={at:e.args[1].value,consoleTimestamp:e.timestamp};});
cdp.on('Network.requestWillBeSent',e=>requests.set(e.requestId,{id:e.requestId,url:e.request.url,start:e.wallTime*1000,monotonic:e.timestamp,initiator:e.initiator,type:e.type}));
for(const event of ['Network.loadingFinished','Network.loadingFailed'])cdp.on(event,e=>{const r=requests.get(e.requestId);if(r){r.finish=r.start+(e.timestamp-r.monotonic)*1000;r.terminal=event;}});
cdp.on('Network.webSocketCreated',e=>websockets.push({url:e.url,afterEnable:!!marker}));
await page.goto(base+'/tests/redactor-browser.html');await page.waitForFunction(()=>window.ready||window.fatal,{},{timeout:120000});assert.equal(await page.evaluate(()=>window.fatal),undefined);assert.ok(marker,'setter marker must arrive');
const cycle=await page.evaluate(async({input,png})=>{const c=window.client;const selected=await c.setInputs([new File([new Uint8Array(input)],'input.pdf'),new File([new Uint8Array(png)],'image.png')]);const masks={0:[{x:.1,y:.1,w:.4,h:.3}]};const pdf=await c.processFile(selected.inputs[0].id,{dpi:150,masksByPage:masks});const image=await c.processFile(selected.inputs[1].id,{dpi:150,masksByPage:masks});const zip=await c.createZip();let code;try{await c.processFile(selected.inputs[0].id,{dpi:150,masksByPage:masks},{onProgress:p=>{if(p.phase==='rendering')c.cancel();}});}catch(e){code=e.code;}const retry=await c.processFile(selected.inputs[0].id,{dpi:150,masksByPage:masks});await c.dispose();return{pass:code==='cancelled'&&retry.blob.size>0,pdfBytes:pdf.blob.size,pngBytes:image.blob.size,zipBytes:zip.size,final:c.diagnostics().totals};},{input,png});assert.equal(cycle.pass,true);await page.waitForTimeout(100);
const all=[...requests.values()];for(const row of all){if(row.finish===undefined){const matches=contextRequests.filter(x=>x.url===row.url&&x.terminal&&x.timing?.responseEnd>=0);if(matches.length===1){row.finish=matches[0].timing.startTime+matches[0].timing.responseEnd;row.terminal=matches[0].terminal;row.terminalSource='Playwright context (worker target terminal not emitted on page CDP)';row.contextTiming=matches[0].timing;}}}for(const row of contextRequests){const start=row.timing?.startTime;if(!(Number.isFinite(start)&&start>0)){assert.ok(all.some(r=>r.url===row.url),'untimed context request must have CDP evidence: '+row.url);continue;}if(!all.some(r=>r.url===row.url&&Math.abs(r.start-start)<2)){all.push({url:row.url,start,finish:row.timing.responseEnd>=0?start+row.timing.responseEnd:undefined,terminal:row.terminal,source:'context-only'});}}const inflightAtEnable=all.filter(r=>r.start<marker.at&&(r.finish===undefined||r.finish>marker.at));const afterEnable=all.filter(r=>/^https?:/.test(r.url)&&r.start>=marker.at);const csp=await page.evaluate(()=>window.__p0Csp);const postCsp=csp.filter(x=>x.at>=marker.at);const recordedAt=await page.evaluate(()=>window.__p0EnabledAt);
await fs.writeFile(output+'/enable-boundary-debug-'+mutant+'.json',JSON.stringify({marker,recordedAt,inflightAtEnable,afterEnable,requests:all,csp,contextRequests},null,2));assert.equal(recordedAt,marker.at);assert.equal(inflightAtEnable.length,0,'all prerequisite requests must settle before disabled=false');assert.equal(workers.length,1);assert.equal(websockets.filter(x=>x.afterEnable).length,0);assert.equal(postCsp.length,0);assert.equal(errors.length,0);
if(mutant){assert.equal(afterEnable.length,1);assert.match(afterEnable[0].url,/p0-enable-window-negative/);assert.equal(afterEnable[0].terminal,'Network.loadingFailed');}
else assert.equal(afterEnable.length,0);
rows.push({mutant,marker,inflightAtEnable,afterEnable,csp,workers,websockets,errors,cycle,requests:all,contextRequests});await context.close();
}
await browser.close();await fs.writeFile(output+'/report.json',JSON.stringify({rows,pass:true,method:'Native input.disabled setter marker before injected request; CDP request wallTime and terminal timestamps reconstruct exact enable boundary. This instrumentation is a test observer, not the security boundary.'},null,2));console.log('PASS: enabled-time inflight0; one real processing cycle HTTP/WS/CSP/errors0; immediate-enable blocked request mutant detected before any networkidle wait');
