import {
  AlignLeft,
  AudioWaveform,
  Braces,
  CalendarDays,
  Clock3,
  Columns3,
  FileSearch2,
  FileSpreadsheet,
  FileStack,
  FileText,
  Files,
  Film,
  Images,
  ImageOff,
  ImageDown,
  LockKeyhole,
  KeyRound,
  Music2,
  QrCode,
  type LucideIcon,
  Rows3,
  ScanText,
  Scissors,
  Sheet,
  Sparkles,
  Table2,
  Undo2,
  WalletCards,
} from "lucide-react";

export type ToolAccent = "green" | "blue" | "violet" | "orange" | "pink" | "sky";
export type ToolCategoryId = "documents" | "media" | "text-data" | "work" | "security-share";

export interface ToolCategoryDefinition {
  id: ToolCategoryId;
  label: string;
  shortLabel: string;
  description: string;
  accent: ToolAccent;
  icon: LucideIcon;
}

export interface ToolDefinition {
  id: string;
  category: ToolCategoryId;
  path: string;
  title: string;
  shortTitle: string;
  description: string;
  eyebrow: string;
  accent: ToolAccent;
  icon: LucideIcon;
  highlights: Array<{ icon: LucideIcon; label: string }>;
  status: "available" | "soon";
}

export const toolCategories: ToolCategoryDefinition[] = [
  { id: "documents", label: "문서·스프레드시트", shortLabel: "문서", description: "문서를 편집·비교·병합하고 필요한 형식으로 변환합니다.", accent: "blue", icon: FileText },
  { id: "media", label: "이미지·영상·오디오", shortLabel: "미디어", description: "이미지와 영상, 오디오를 브라우저에서 직접 편집합니다.", accent: "pink", icon: Images },
  { id: "text-data", label: "텍스트·데이터", shortLabel: "텍스트·데이터", description: "텍스트와 코드, 표 데이터를 읽기 좋은 형태로 정리합니다.", accent: "violet", icon: Braces },
  { id: "work", label: "일정·근무·급여", shortLabel: "업무 계산", description: "업무 일정과 근무일, 시차와 급여를 간편하게 계산합니다.", accent: "green", icon: CalendarDays },
  { id: "security-share", label: "보안·공유", shortLabel: "보안·공유", description: "개인정보를 보호하고 안전한 비밀번호와 공유용 QR을 만듭니다.", accent: "orange", icon: LockKeyhole },
];

export const tools: ToolDefinition[] = [
  {
    id: "excel-merger",
    category: "documents",
    path: "/tools/excel-merger",
    title: "Excel Merger",
    shortTitle: "Excel 병합",
    description: "여러 Excel 파일과 CSV를 원하는 방식으로 하나의 파일에 정리합니다.",
    eyebrow: "스프레드시트",
    accent: "green",
    icon: FileSpreadsheet,
    highlights: [
      { icon: Sheet, label: "시트별 병합" },
      { icon: Rows3, label: "세로 병합" },
      { icon: Columns3, label: "가로 병합" },
      { icon: LockKeyhole, label: "빈 영역·암호" },
    ],
    status: "available",
  },
  {
    id: "pdf-editor",
    category: "documents",
    path: "/tools/pdf-editor",
    title: "PDF Tools",
    shortTitle: "PDF 도구",
    description: "PDF 페이지를 편집·병합·범위별 추출하고 이미지·DOCX·XLSX·TXT로 변환하거나 브라우저 OCR을 실행합니다.",
    eyebrow: "PDF 편집·변환",
    accent: "violet",
    icon: FileStack,
    highlights: [
      { icon: Files, label: "편집·범위 추출" },
      { icon: ImageDown, label: "이미지 변환" },
      { icon: FileText, label: "DOCX·TXT" },
      { icon: FileSpreadsheet, label: "XLSX·OCR" },
    ],
    status: "available",
  },
  {
    id: "word-compare",
    category: "documents",
    path: "/tools/word-compare",
    title: "Word Compare",
    shortTitle: "Word 비교",
    description: "수정 전후 Word 문서의 본문·표·서식 변경을 비교하고 웹·Excel·변경 추적 DOCX로 확인합니다.",
    eyebrow: "문서 비교",
    accent: "blue",
    icon: FileSearch2,
    highlights: [
      { icon: FileSearch2, label: "문단·문장 Diff" },
      { icon: Rows3, label: "표 변경 확인" },
      { icon: FileSpreadsheet, label: "Excel 보고서" },
      { icon: Files, label: "다중 동시 비교" },
    ],
    status: "available",
  },
  {
    id: "hwp-editor",
    category: "documents",
    path: "/tools/hwp-editor",
    title: "HWP Editor",
    shortTitle: "HWP 편집",
    description: "HWP·HWPX 문서를 공식 rhwp Studio에서 편집하고 다시 HWP·HWPX로 저장합니다.",
    eyebrow: "한글 문서",
    accent: "orange",
    icon: ScanText,
    highlights: [
      { icon: FileText, label: "HWP·HWPX·HML" },
      { icon: ScanText, label: "전체 문서 편집" },
      { icon: Rows3, label: "서식·표·개체" },
      { icon: LockKeyhole, label: "암호 문서" },
    ],
    status: "available",
  },
  {
    id: "hwp-compare",
    category: "documents",
    path: "/tools/hwp-compare",
    title: "HWP Compare",
    shortTitle: "HWP 비교",
    description: "수정 전후 HWP·HWPX 문서의 본문·표·개요 번호 변경을 웹과 Excel에서 확인합니다.",
    eyebrow: "한글 문서 비교",
    accent: "orange",
    icon: FileSearch2,
    highlights: [
      { icon: FileSearch2, label: "문단·문장 Diff" },
      { icon: Rows3, label: "표 구조 비교" },
      { icon: FileSpreadsheet, label: "Excel 보고서" },
      { icon: Files, label: "다중 동시 비교" },
    ],
    status: "available",
  },
  {
    id: "video-studio",
    category: "media",
    path: "/tools/video-studio/",
    title: "Video Studio",
    shortTitle: "비디오 스튜디오",
    description: "영상 수 제한 없이 최대 10개 그룹으로 편집하고 영상·오디오 스트림을 원하는 방식으로 변환합니다.",
    eyebrow: "비디오 편집",
    accent: "pink",
    icon: Film,
    highlights: [
      { icon: Film, label: "무제한 추가·10개 그룹" },
      { icon: Scissors, label: "무손실 빠른 자르기" },
      { icon: Files, label: "개별 저장·선택 ZIP" },
      { icon: Music2, label: "영상 속 음성 제어" },
    ],
    status: "available",
  },
  {
    id: "audio-studio",
    category: "media",
    path: "/tools/audio-studio",
    title: "Audio Waveform Studio",
    shortTitle: "오디오 편집기",
    description: "오디오 파형에서 구간을 편집하거나 피치·음색을 변조하고 WAV·MP3로 저장합니다.",
    eyebrow: "오디오 편집",
    accent: "violet",
    icon: AudioWaveform,
    highlights: [
      { icon: AudioWaveform, label: "고해상도 파형" },
      { icon: Scissors, label: "구간 편집" },
      { icon: Undo2, label: "음성 효과·Undo" },
      { icon: Music2, label: "WAV·MP3" },
    ],
    status: "available",
  },
  {
    id: "image-studio",
    category: "media",
    path: "/tools/image-studio",
    title: "Image Studio",
    shortTitle: "이미지 스튜디오",
    description: "사진 보정과 자유 그리기를 한 편집기에서 사용하고 여러 파일은 일괄 편집·콜라주·GIF로 만듭니다.",
    eyebrow: "이미지 편집",
    accent: "sky",
    icon: Images,
    highlights: [
      { icon: Sparkles, label: "사진·그리기 통합" },
      { icon: Images, label: "일괄 리사이즈" },
      { icon: FileStack, label: "콜라주" },
      { icon: Film, label: "GIF 애니메이션" },
    ],
    status: "available",
  },
  {
    id: "text-tools",
    category: "text-data",
    path: "/tools/text-tools",
    title: "Text Tools",
    shortTitle: "텍스트 정돈",
    description: "공백·줄바꿈을 정리하고 케이스 변환과 로컬 한국어 문장 검사를 실행합니다.",
    eyebrow: "텍스트 생산성",
    accent: "blue",
    icon: AlignLeft,
    highlights: [
      { icon: AlignLeft, label: "공백·줄 정돈" },
      { icon: Sparkles, label: "중복 줄 제거" },
      { icon: Braces, label: "Case 변환" },
      { icon: ScanText, label: "한국어 가이드" },
    ],
    status: "available",
  },
  {
    id: "text-formatter",
    category: "text-data",
    path: "/tools/text-formatter",
    title: "Code Formatter",
    shortTitle: "코드 포맷터",
    description: "JSON·SQL·XML 문법을 검사하고 들여쓰기 또는 한 줄 형식으로 정돈합니다.",
    eyebrow: "개발·데이터",
    accent: "violet",
    icon: Braces,
    highlights: [
      { icon: Braces, label: "JSON" },
      { icon: FileText, label: "SQL" },
      { icon: ScanText, label: "XML" },
      { icon: Sparkles, label: "오류 탐지" },
    ],
    status: "available",
  },
  {
    id: "work-calculator",
    category: "work",
    path: "/tools/work-calculator",
    title: "Workday Calculator",
    shortTitle: "영업일·연차",
    description: "대한민국 공휴일을 제외한 영업일과 입사일·회계연도 기준 연차를 계산합니다.",
    eyebrow: "근무 일정",
    accent: "green",
    icon: CalendarDays,
    highlights: [
      { icon: CalendarDays, label: "영업일" },
      { icon: Sparkles, label: "대체공휴일" },
      { icon: Rows3, label: "입사일 기준" },
      { icon: Columns3, label: "회계연도 기준" },
    ],
    status: "available",
  },
  {
    id: "timezone-calculator",
    category: "work",
    path: "/tools/timezone-calculator",
    title: "World Time Planner",
    shortTitle: "글로벌 시차",
    description: "세계지도에서 도시를 선택해 현지 시각과 모두가 근무 중인 글로벌 회의 시간대를 찾습니다.",
    eyebrow: "글로벌 협업",
    accent: "sky",
    icon: Clock3,
    highlights: [
      { icon: Clock3, label: "세계지도 도시 핀" },
      { icon: Sparkles, label: "서머타임" },
      { icon: Rows3, label: "근무시간 중첩" },
      { icon: FileStack, label: "44개 주요 도시" },
    ],
    status: "available",
  },
  {
    id: "payroll-calculator",
    category: "work",
    path: "/tools/payroll-calculator",
    title: "Payroll Calculator",
    shortTitle: "급여 계산",
    description: "주휴수당·월 실수령액·퇴직금을 최신 기준으로 브라우저에서 간이 계산합니다.",
    eyebrow: "급여·노무",
    accent: "orange",
    icon: WalletCards,
    highlights: [
      { icon: Clock3, label: "주휴수당" },
      { icon: WalletCards, label: "실수령액" },
      { icon: FileSpreadsheet, label: "4대 보험" },
      { icon: LockKeyhole, label: "퇴직금" },
    ],
    status: "available",
  },
  {
    id: "image-privacy",
    category: "security-share",
    path: "/tools/image-privacy",
    title: "Image Privacy",
    shortTitle: "사진 정보 제거",
    description: "JPG·PNG에 숨은 GPS·촬영 기기·시각 정보(EXIF)를 확인하고 제거합니다.",
    eyebrow: "사진 개인정보",
    accent: "pink",
    icon: ImageOff,
    highlights: [
      { icon: ScanText, label: "숨은 정보 확인" },
      { icon: ImageOff, label: "GPS 제거" },
      { icon: Images, label: "JPG·PNG" },
      { icon: LockKeyhole, label: "브라우저 처리" },
    ],
    status: "available",
  },
  {
    id: "security-tools",
    category: "security-share",
    path: "/tools/security-tools",
    title: "Password Generator",
    shortTitle: "비밀번호 생성기",
    description: "운영체제의 보안 난수로 비밀번호를 만들고 패턴 기반 추측 난이도를 확인합니다.",
    eyebrow: "보안 도구",
    accent: "violet",
    icon: KeyRound,
    highlights: [
      { icon: KeyRound, label: "보안 난수 생성" },
      { icon: LockKeyhole, label: "강도 분석" },
      { icon: Clock3, label: "해독 시간 추정" },
      { icon: Sparkles, label: "최대 64자" },
    ],
    status: "available",
  },
  {
    id: "qr-studio",
    category: "security-share",
    path: "/tools/qr-studio",
    title: "QR Studio",
    shortTitle: "QR 스튜디오",
    description: "URL·텍스트 QR 코드를 만들고 휴대폰 카메라나 사진에서 QR 데이터를 읽습니다.",
    eyebrow: "QR 생성·스캔",
    accent: "blue",
    icon: QrCode,
    highlights: [
      { icon: QrCode, label: "QR 생성" },
      { icon: Images, label: "중앙 로고" },
      { icon: ScanText, label: "카메라·사진 스캔" },
      { icon: ImageDown, label: "PNG 저장" },
    ],
    status: "available",
  },
  {
    id: "data-converter",
    category: "text-data",
    path: "/tools/data-converter",
    title: "Table Converter",
    shortTitle: "표 데이터 변환",
    description: "CSV·JSON·HTML 표 데이터를 서로 변환하고 파일 또는 클립보드로 내보냅니다.",
    eyebrow: "표 데이터",
    accent: "green",
    icon: Table2,
    highlights: [
      { icon: FileSpreadsheet, label: "CSV" },
      { icon: Braces, label: "JSON" },
      { icon: Table2, label: "HTML 표" },
      { icon: LockKeyhole, label: "브라우저 변환" },
    ],
    status: "available",
  },
];
