import {
  AlignLeft,
  Braces,
  CalendarDays,
  Clock3,
  Columns3,
  FileSearch2,
  FileSpreadsheet,
  FileStack,
  FileText,
  Files,
  Film,
  Images,
  ImageOff,
  ImageDown,
  LockKeyhole,
  KeyRound,
  Music2,
  QrCode,
  type LucideIcon,
  Rows3,
  ScanText,
  Scissors,
  Sheet,
  Sparkles,
  Table2,
  WalletCards,
} from "lucide-react";

export type ToolAccent = "green" | "blue" | "violet" | "orange" | "pink" | "sky";

export interface ToolDefinition {
  id: string;
  path: string;
  title: string;
  shortTitle: string;
  description: string;
  eyebrow: string;
  accent: ToolAccent;
  icon: LucideIcon;
  highlights: Array<{ icon: LucideIcon; label: string }>;
  status: "available" | "soon";
}

export const tools: ToolDefinition[] = [
  {
    id: "excel-merger",
    path: "/tools/excel-merger",
    title: "Excel Merger",
    shortTitle: "Excel 병합",
    description: "여러 Excel 파일과 CSV를 원하는 방식으로 하나의 파일에 정리합니다.",
    eyebrow: "스프레드시트",
    accent: "green",
    icon: FileSpreadsheet,
    highlights: [
      { icon: Sheet, label: "시트별 병합" },
      { icon: Rows3, label: "세로 병합" },
      { icon: Columns3, label: "가로 병합" },
      { icon: LockKeyhole, label: "SheetTrim·암호" },
    ],
    status: "available",
  },
  {
    id: "pdf-editor",
    path: "/tools/pdf-editor",
    title: "PDF Tools",
    shortTitle: "PDF 도구",
    description: "PDF 페이지를 편집·병합·범위별 추출하고 이미지·DOCX·XLSX·TXT로 변환하거나 브라우저 OCR을 실행합니다.",
    eyebrow: "PDF 편집·변환",
    accent: "violet",
    icon: FileStack,
    highlights: [
      { icon: Files, label: "편집·범위 추출" },
      { icon: ImageDown, label: "이미지 변환" },
      { icon: FileText, label: "DOCX·TXT" },
      { icon: FileSpreadsheet, label: "XLSX·OCR" },
    ],
    status: "available",
  },
  {
    id: "word-compare",
    path: "/tools/word-compare",
    title: "Word Compare",
    shortTitle: "Word 비교",
    description: "수정 전후 Word 문서의 본문·표·서식 변경을 비교하고 웹·Excel·변경 추적 DOCX로 확인합니다.",
    eyebrow: "문서 비교",
    accent: "blue",
    icon: FileSearch2,
    highlights: [
      { icon: FileSearch2, label: "문단·문장 Diff" },
      { icon: Rows3, label: "표 변경 확인" },
      { icon: FileSpreadsheet, label: "Excel 보고서" },
      { icon: Files, label: "다중 동시 비교" },
    ],
    status: "available",
  },
  {
    id: "hwp-editor",
    path: "/tools/hwp-editor",
    title: "HWP Editor",
    shortTitle: "HWP 편집",
    description: "HWP·HWPX 문서를 공식 rhwp Studio에서 편집하고 다시 HWP·HWPX로 저장합니다.",
    eyebrow: "한글 문서",
    accent: "orange",
    icon: ScanText,
    highlights: [
      { icon: FileText, label: "HWP·HWPX·HML" },
      { icon: ScanText, label: "전체 문서 편집" },
      { icon: Rows3, label: "서식·표·개체" },
      { icon: LockKeyhole, label: "암호 문서" },
    ],
    status: "available",
  },
  {
    id: "hwp-compare",
    path: "/tools/hwp-compare",
    title: "HWP Compare",
    shortTitle: "HWP 비교",
    description: "수정 전후 HWP·HWPX 문서의 본문·표·개요 번호 변경을 웹과 Excel에서 확인합니다.",
    eyebrow: "한글 문서 비교",
    accent: "orange",
    icon: FileSearch2,
    highlights: [
      { icon: FileSearch2, label: "문단·문장 Diff" },
      { icon: Rows3, label: "표 구조 비교" },
      { icon: FileSpreadsheet, label: "Excel 보고서" },
      { icon: Files, label: "다중 동시 비교" },
    ],
    status: "available",
  },
  {
    id: "video-studio",
    path: "/tools/video-studio",
    title: "Video Studio",
    shortTitle: "비디오 스튜디오",
    description: "최대 6개 영상을 6개 그룹으로 나누고 그룹별 구간·동기 재생·개별 출력·이어붙이기를 설정합니다.",
    eyebrow: "비디오 편집",
    accent: "pink",
    icon: Film,
    highlights: [
      { icon: Film, label: "최대 6개 그룹" },
      { icon: Scissors, label: "패스스루 자르기" },
      { icon: Files, label: "그룹별 개별·연결" },
      { icon: Music2, label: "GIF·MP3·AAC" },
    ],
    status: "available",
  },
  {
    id: "image-studio",
    path: "/tools/image-studio",
    title: "Image Studio",
    shortTitle: "이미지 스튜디오",
    description: "이미지를 꾸미고 여러 파일을 일괄 편집하거나 콜라주와 GIF로 만듭니다.",
    eyebrow: "이미지 편집",
    accent: "sky",
    icon: Images,
    highlights: [
      { icon: Sparkles, label: "레이어 편집" },
      { icon: Images, label: "일괄 리사이즈" },
      { icon: FileStack, label: "콜라주" },
      { icon: Film, label: "GIF 애니메이션" },
    ],
    status: "available",
  },
  {
    id: "text-tools",
    path: "/tools/text-tools",
    title: "Text Tools",
    shortTitle: "텍스트 정돈",
    description: "공백·줄바꿈을 정리하고 케이스 변환과 로컬 한국어 문장 검사를 실행합니다.",
    eyebrow: "텍스트 생산성",
    accent: "blue",
    icon: AlignLeft,
    highlights: [
      { icon: AlignLeft, label: "공백·줄 정돈" },
      { icon: Sparkles, label: "중복 줄 제거" },
      { icon: Braces, label: "Case 변환" },
      { icon: ScanText, label: "한국어 가이드" },
    ],
    status: "available",
  },
  {
    id: "text-formatter",
    path: "/tools/text-formatter",
    title: "Code Formatter",
    shortTitle: "코드 포맷터",
    description: "JSON·SQL·XML 문법을 검사하고 들여쓰기 또는 한 줄 형식으로 정돈합니다.",
    eyebrow: "개발·데이터",
    accent: "violet",
    icon: Braces,
    highlights: [
      { icon: Braces, label: "JSON" },
      { icon: FileText, label: "SQL" },
      { icon: ScanText, label: "XML" },
      { icon: Sparkles, label: "오류 탐지" },
    ],
    status: "available",
  },
  {
    id: "work-calculator",
    path: "/tools/work-calculator",
    title: "Workday Calculator",
    shortTitle: "영업일·연차",
    description: "대한민국 공휴일을 제외한 영업일과 입사일·회계연도 기준 연차를 계산합니다.",
    eyebrow: "근무 일정",
    accent: "green",
    icon: CalendarDays,
    highlights: [
      { icon: CalendarDays, label: "영업일" },
      { icon: Sparkles, label: "대체공휴일" },
      { icon: Rows3, label: "입사일 기준" },
      { icon: Columns3, label: "회계연도 기준" },
    ],
    status: "available",
  },
  {
    id: "timezone-calculator",
    path: "/tools/timezone-calculator",
    title: "World Time Planner",
    shortTitle: "글로벌 시차",
    description: "세계지도에서 도시를 선택해 현지 시각과 모두가 근무 중인 글로벌 회의 시간대를 찾습니다.",
    eyebrow: "글로벌 협업",
    accent: "sky",
    icon: Clock3,
    highlights: [
      { icon: Clock3, label: "세계지도 도시 핀" },
      { icon: Sparkles, label: "서머타임" },
      { icon: Rows3, label: "근무시간 중첩" },
      { icon: FileStack, label: "44개 주요 도시" },
    ],
    status: "available",
  },
  {
    id: "payroll-calculator",
    path: "/tools/payroll-calculator",
    title: "Payroll Calculator",
    shortTitle: "급여 계산",
    description: "주휴수당·월 실수령액·퇴직금을 최신 기준으로 브라우저에서 간이 계산합니다.",
    eyebrow: "급여·노무",
    accent: "orange",
    icon: WalletCards,
    highlights: [
      { icon: Clock3, label: "주휴수당" },
      { icon: WalletCards, label: "실수령액" },
      { icon: FileSpreadsheet, label: "4대 보험" },
      { icon: LockKeyhole, label: "퇴직금" },
    ],
    status: "available",
  },
  {
    id: "image-privacy",
    path: "/tools/image-privacy",
    title: "Image Privacy",
    shortTitle: "사진 정보 제거",
    description: "사진의 GPS·촬영 기기·시각을 확인하고 EXIF 없는 깨끗한 사본을 만듭니다.",
    eyebrow: "사진 개인정보",
    accent: "pink",
    icon: ImageOff,
    highlights: [
      { icon: ScanText, label: "EXIF 확인" },
      { icon: ImageOff, label: "GPS 제거" },
      { icon: Images, label: "JPG·PNG" },
      { icon: LockKeyhole, label: "Worker 처리" },
    ],
    status: "available",
  },
  {
    id: "security-tools",
    path: "/tools/security-tools",
    title: "Password Security",
    shortTitle: "비밀번호 보안",
    description: "암호학적 난수로 비밀번호를 만들고 패턴·엔트로피 기반 강도를 측정합니다.",
    eyebrow: "보안 도구",
    accent: "violet",
    icon: KeyRound,
    highlights: [
      { icon: KeyRound, label: "CSPRNG 생성" },
      { icon: LockKeyhole, label: "강도 분석" },
      { icon: Clock3, label: "공격 시간" },
      { icon: Sparkles, label: "최대 64자" },
    ],
    status: "available",
  },
  {
    id: "qr-studio",
    path: "/tools/qr-studio",
    title: "QR Studio",
    shortTitle: "QR 스튜디오",
    description: "URL·텍스트 QR 코드를 만들고 업로드한 사진 속 QR 데이터를 읽습니다.",
    eyebrow: "QR 생성·스캔",
    accent: "blue",
    icon: QrCode,
    highlights: [
      { icon: QrCode, label: "QR 생성" },
      { icon: Images, label: "중앙 로고" },
      { icon: ScanText, label: "사진 스캔" },
      { icon: ImageDown, label: "PNG 저장" },
    ],
    status: "available",
  },
  {
    id: "data-converter",
    path: "/tools/data-converter",
    title: "Table Converter",
    shortTitle: "표 데이터 변환",
    description: "CSV·JSON·HTML Table 데이터를 서로 변환하고 파일 또는 클립보드로 내보냅니다.",
    eyebrow: "표 데이터",
    accent: "green",
    icon: Table2,
    highlights: [
      { icon: FileSpreadsheet, label: "CSV" },
      { icon: Braces, label: "JSON" },
      { icon: Table2, label: "HTML Table" },
      { icon: LockKeyhole, label: "Worker 파싱" },
    ],
    status: "available",
  },
];
