import { Banknote, Calculator, Landmark, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { useTranslation } from "react-i18next";

import { PrivacyBanner } from "../../components/PrivacyBanner";
import { PageHeader, SegmentedControl } from "../../components/ui";
import { buttonVariants } from "../../components/ui/button";
import { ToolGuide } from "../../components/ToolGuide";
import {
  UtilityField,
  UtilityInput,
  UtilityNotice,
  UtilityPage,
  UtilitySectionCard,
} from "../../components/UtilitySurface";
import { localIsoDate } from "../../utils/date";
import { calculateNetPay, calculateSeverance, calculateWeeklyAllowance, PAYROLL_STANDARD } from "./payroll";

type PayrollMode = "weekly" | "net" | "severance";
export function PayrollCalculatorPage() {
  const { t, i18n } = useTranslation("features");
  const won = new Intl.NumberFormat(i18n.language === "en" ? "en-US" : "ko-KR", { style: "currency", currency: "KRW", maximumFractionDigits: 0 });
  const [mode, setMode] = useState<PayrollMode>("weekly");
  const [hours, setHours] = useState(40); const [wage, setWage] = useState(10_500);
  const [salary, setSalary] = useState(3_000_000); const [dependents, setDependents] = useState(1); const [children, setChildren] = useState(0);
  const [hireDate, setHireDate] = useState("2023-01-01"); const [retirementDate, setRetirementDate] = useState(() => localIsoDate());
  const [severanceWeeklyHours, setSeveranceWeeklyHours] = useState(40);
  const [threeMonthWages, setThreeMonthWages] = useState(9_000_000); const [annualBonus, setAnnualBonus] = useState(0); const [annualLeavePay, setAnnualLeavePay] = useState(0); const [periodDays, setPeriodDays] = useState(92);
  const weekly = calculateWeeklyAllowance(hours, wage); const net = calculateNetPay(salary, dependents, children);
  const severance = calculateSeverance({ hireDate, retirementDate, wagesThreeMonths: threeMonthWages, annualBonus, annualLeavePay, periodDays, weeklyHours: severanceWeeklyHours });
  const fieldGridClassName = "grid grid-cols-3 gap-[11px] max-[620px]:grid-cols-1";

  return <UtilityPage toolId="payroll-calculator">
    <PageHeader eyebrow="PAYROLL" title={t("payroll.title")} description={t("payroll.description")}><PrivacyBanner compact /></PageHeader>
    <UtilityNotice className="mt-1 mb-[18px]" tone="success"><ShieldCheck className="mt-0.5 shrink-0" size={20} /><strong>{t("payroll.koreanNotice")}</strong></UtilityNotice>
    <div className="mb-4 mt-1 rounded-2xl bg-muted p-1" data-testid="payroll-mode"><SegmentedControl value={mode} onChange={setMode} label={t("payroll.modeLabel")} options={[{ value: "weekly", label: t("payroll.weekly") }, { value: "net", label: t("payroll.net") }, { value: "severance", label: t("payroll.severance") }]} /></div>
    {mode === "weekly" && <><UtilitySectionCard title={t("payroll.conditions")}><div className={fieldGridClassName}><NumberInput label={t("payroll.weeklyHours")} value={hours} onChange={setHours} suffix={t("payroll.hours")} /><NumberInput label={t("payroll.hourlyWage")} value={wage} onChange={setWage} suffix={t("payroll.won")} /></div></UtilitySectionCard><PayrollHero icon={<Banknote />} value={won.format(weekly.allowance)} label={weekly.eligible ? t("payroll.weeklyEligible", { hours: weekly.paidHours.toFixed(1) }) : t("payroll.weeklyIneligible")} /></>}
    {mode === "net" && <><UtilitySectionCard title={t("payroll.payInfo")}><div className={fieldGridClassName}><NumberInput label={t("payroll.taxableSalary")} value={salary} onChange={setSalary} suffix={t("payroll.won")} help={t("payroll.taxableHelp")} /><NumberInput label={t("payroll.dependents")} value={dependents} onChange={setDependents} suffix={t("payroll.people")} /><NumberInput label={t("payroll.children")} value={children} onChange={setChildren} suffix={t("payroll.people")} /></div></UtilitySectionCard><PayrollHero icon={<Calculator />} value={won.format(net.net)} label={t("payroll.estimatedNet")} /><UtilitySectionCard title={t("payroll.deductions")}><dl className="m-0" data-testid="payroll-breakdown"><Row label={t("payroll.pension")} value={net.pension} formatter={won} /><Row label={t("payroll.health")} value={net.health} formatter={won} /><Row label={t("payroll.care")} value={net.longTermCare} formatter={won} /><Row label={t("payroll.employment")} value={net.employment} formatter={won} /><Row label={t("payroll.incomeTax")} value={net.incomeTax} formatter={won} /><Row label={t("payroll.localTax")} value={net.localTax} formatter={won} /><Row label={t("payroll.deductionTotal")} value={net.deductions} formatter={won} total /></dl></UtilitySectionCard></>}
    {mode === "severance" && <><UtilitySectionCard title={t("payroll.servicePay")}><div className={fieldGridClassName}><UtilityField><span>{t("payroll.hireDate")}</span><UtilityInput type="date" value={hireDate} onChange={(event) => setHireDate(event.target.value)} /></UtilityField><UtilityField><span>{t("payroll.retirementDate")}</span><UtilityInput type="date" value={retirementDate} onChange={(event) => setRetirementDate(event.target.value)} /></UtilityField><NumberInput label={t("payroll.severanceWeeklyHours")} value={severanceWeeklyHours} onChange={setSeveranceWeeklyHours} suffix={t("payroll.hours")} help={t("payroll.severanceWeeklyHoursHelp")} /><NumberInput label={t("payroll.wagesThreeMonths")} value={threeMonthWages} onChange={setThreeMonthWages} suffix={t("payroll.won")} /><NumberInput label={t("payroll.annualBonus")} value={annualBonus} onChange={setAnnualBonus} suffix={t("payroll.won")} /><NumberInput label={t("payroll.annualLeavePay")} value={annualLeavePay} onChange={setAnnualLeavePay} suffix={t("payroll.won")} /><NumberInput label={t("payroll.periodDays")} value={periodDays} onChange={setPeriodDays} suffix={t("payroll.days")} help={t("payroll.periodDaysHelp")} /></div></UtilitySectionCard><PayrollHero icon={<Landmark />} value={won.format(severance.severance)} label={severance.eligible ? t("payroll.severanceEligible", { average: won.format(severance.averageDailyWage), days: severance.serviceDays }) : t("payroll.severanceIneligible")} /></>}
    <UtilityNotice className="mb-[18px]" tone="success"><ShieldCheck className="mt-0.5 shrink-0" size={20} /><p><strong className="block">{t("payroll.standard", { date: PAYROLL_STANDARD.effectiveDate })}</strong><span className="mt-1 block text-xs text-muted-foreground">{t("payroll.rates", { pension: formatRate(PAYROLL_STANDARD.pensionEmployeeRate), health: formatRate(PAYROLL_STANDARD.healthEmployeeRate), care: formatRate(PAYROLL_STANDARD.longTermCareToHealthRate), employment: formatRate(PAYROLL_STANDARD.employmentEmployeeRate) })}</span></p></UtilityNotice>
    <nav className="-mt-2 mb-[18px] flex flex-wrap gap-2" aria-label={t("payroll.sourcesLabel")}><a className={buttonVariants({ variant: "secondary", size: "sm", className: "rounded-full text-xs font-bold text-amber-800 dark:text-amber-300" })} href="https://www.nps.or.kr/pnsinfo/ntpsklg/getOHAF0038M0.do?menuId=MN24001113&tab=tab5" target="_blank" rel="noreferrer">{t("payroll.pensionSource")}</a><a className={buttonVariants({ variant: "secondary", size: "sm", className: "rounded-full text-xs font-bold text-amber-800 dark:text-amber-300" })} href="https://edi.nhis.or.kr/portal/images/popup/20251204_pop01longdesc.html" target="_blank" rel="noreferrer">{t("payroll.healthSource")}</a><a className={buttonVariants({ variant: "secondary", size: "sm", className: "rounded-full text-xs font-bold text-amber-800 dark:text-amber-300" })} href="https://mob.tbht.hometax.go.kr/jsonAction.do?actionId=UTBSFAAM06F001" target="_blank" rel="noreferrer">{t("payroll.taxSource")}</a></nav>
    <ToolGuide title={t("payroll.guide.title")} description={t("payroll.guide.description")} blocks={(t("payroll.guide.blocks", { returnObjects: true }) as Array<{title:string;text:string}>).map((item) => ({ title: item.title, paragraphs: [item.text] }))} faq={(t("payroll.guide.faq", { returnObjects: true }) as Array<{q:string;a:string}>).map((item) => ({ question: item.q, answer: item.a }))} />
  </UtilityPage>;
}

function NumberInput({ label, value, onChange, suffix, help }: { label: string; value: number; onChange: (value: number) => void; suffix: string; help?: string }) { return <UtilityField><span>{label}</span><div className="flex min-w-0 items-center overflow-hidden rounded-xl border border-input bg-background"><UtilityInput className="border-0 bg-transparent ring-0 focus-visible:ring-0" type="number" min={0} value={value} onChange={(event) => onChange(Math.max(0, Number(event.target.value)))} /><b className="shrink-0 pr-3 text-xs text-muted-foreground">{suffix}</b></div>{help && <small className="text-xs font-medium text-muted-foreground">{help}</small>}</UtilityField>; }
function PayrollHero({ icon, value, label }: { icon: React.ReactNode; value: string; label: string }) { return <div className="mb-[15px] flex items-center gap-4 rounded-2xl border border-orange-200 bg-orange-50/70 p-5 text-orange-700 dark:border-orange-900 dark:bg-orange-950/40 dark:text-orange-300" data-testid="payroll-result">{icon}<div><strong className="block text-3xl tracking-[-.045em] text-foreground">{value}</strong><p className="mt-1 text-sm text-muted-foreground">{label}</p></div></div>; }
function Row({ label, value, formatter, total = false }: { label: string; value: number; formatter: Intl.NumberFormat; total?: boolean }) { return <div className={`flex justify-between gap-5 px-1 py-2.5 text-sm ${total ? "mt-1 border-0 font-bold text-orange-700 dark:text-orange-300" : "border-b border-border"}`}><dt className={total ? undefined : "text-muted-foreground"}>{label}</dt><dd className="m-0 font-bold">{formatter.format(value)}</dd></div>; }
function formatRate(rate: number) { return Number((rate * 100).toFixed(3)).toString(); }
