import { Banknote, Calculator, Landmark, ShieldCheck } from "lucide-react";
import { useState } from "react";
import { useTranslation } from "react-i18next";

import { PrivacyBanner } from "../../components/PrivacyBanner";
import { PageHeader, SectionCard, SegmentedControl } from "../../components/ui";
import { ToolGuide } from "../../components/ToolGuide";
import { calculateNetPay, calculateSeverance, calculateWeeklyAllowance, PAYROLL_STANDARD } from "./payroll";

type PayrollMode = "weekly" | "net" | "severance";
export function PayrollCalculatorPage() {
  const { t, i18n } = useTranslation("features");
  const won = new Intl.NumberFormat(i18n.language === "en" ? "en-US" : "ko-KR", { style: "currency", currency: "KRW", maximumFractionDigits: 0 });
  const [mode, setMode] = useState<PayrollMode>("weekly");
  const [hours, setHours] = useState(40); const [wage, setWage] = useState(10_500);
  const [salary, setSalary] = useState(3_000_000); const [dependents, setDependents] = useState(1); const [children, setChildren] = useState(0);
  const [hireDate, setHireDate] = useState("2023-01-01"); const [retirementDate, setRetirementDate] = useState(new Date().toISOString().slice(0, 10));
  const [threeMonthWages, setThreeMonthWages] = useState(9_000_000); const [annualBonus, setAnnualBonus] = useState(0); const [annualLeavePay, setAnnualLeavePay] = useState(0); const [periodDays, setPeriodDays] = useState(92);
  const weekly = calculateWeeklyAllowance(hours, wage); const net = calculateNetPay(salary, dependents, children);
  const severance = calculateSeverance({ hireDate, retirementDate, wagesThreeMonths: threeMonthWages, annualBonus, annualLeavePay, periodDays, weeklyHours: hours });
  return <div className="page tool-page page-enter utility-page payroll-page">
    <PageHeader eyebrow="PAYROLL" title={t("payroll.title")} description={t("payroll.description")}><PrivacyBanner compact /></PageHeader>
    <div className="standard-notice"><ShieldCheck size={20} /><p><strong>{t("payroll.koreanNotice")}</strong></p></div>
    <div className="mode-switch"><SegmentedControl value={mode} onChange={setMode} label={t("payroll.modeLabel")} options={[{ value: "weekly", label: t("payroll.weekly") }, { value: "net", label: t("payroll.net") }, { value: "severance", label: t("payroll.severance") }]} /></div>
    {mode === "weekly" && <><SectionCard title={t("payroll.conditions")}><div className="utility-form-grid"><NumberInput label={t("payroll.weeklyHours")} value={hours} onChange={setHours} suffix={t("payroll.hours")} /><NumberInput label={t("payroll.hourlyWage")} value={wage} onChange={setWage} suffix={t("payroll.won")} /></div></SectionCard><PayrollHero icon={<Banknote />} value={won.format(weekly.allowance)} label={weekly.eligible ? t("payroll.weeklyEligible", { hours: weekly.paidHours.toFixed(1) }) : t("payroll.weeklyIneligible")} /></>}
    {mode === "net" && <><SectionCard title={t("payroll.payInfo")}><div className="utility-form-grid"><NumberInput label={t("payroll.taxableSalary")} value={salary} onChange={setSalary} suffix={t("payroll.won")} help={t("payroll.taxableHelp")} /><NumberInput label={t("payroll.dependents")} value={dependents} onChange={setDependents} suffix={t("payroll.people")} /><NumberInput label={t("payroll.children")} value={children} onChange={setChildren} suffix={t("payroll.people")} /></div></SectionCard><PayrollHero icon={<Calculator />} value={won.format(net.net)} label={t("payroll.estimatedNet")} /><SectionCard title={t("payroll.deductions")}><dl className="payroll-breakdown"><Row label={t("payroll.pension")} value={net.pension} formatter={won} /><Row label={t("payroll.health")} value={net.health} formatter={won} /><Row label={t("payroll.care")} value={net.longTermCare} formatter={won} /><Row label={t("payroll.employment")} value={net.employment} formatter={won} /><Row label={t("payroll.incomeTax")} value={net.incomeTax} formatter={won} /><Row label={t("payroll.localTax")} value={net.localTax} formatter={won} /><Row label={t("payroll.deductionTotal")} value={net.deductions} formatter={won} total /></dl></SectionCard></>}
    {mode === "severance" && <><SectionCard title={t("payroll.servicePay")}><div className="utility-form-grid"><label><span>{t("payroll.hireDate")}</span><input type="date" value={hireDate} onChange={(event) => setHireDate(event.target.value)} /></label><label><span>{t("payroll.retirementDate")}</span><input type="date" value={retirementDate} onChange={(event) => setRetirementDate(event.target.value)} /></label><NumberInput label={t("payroll.wagesThreeMonths")} value={threeMonthWages} onChange={setThreeMonthWages} suffix={t("payroll.won")} /><NumberInput label={t("payroll.annualBonus")} value={annualBonus} onChange={setAnnualBonus} suffix={t("payroll.won")} /><NumberInput label={t("payroll.annualLeavePay")} value={annualLeavePay} onChange={setAnnualLeavePay} suffix={t("payroll.won")} /><NumberInput label={t("payroll.periodDays")} value={periodDays} onChange={setPeriodDays} suffix={t("payroll.days")} help={t("payroll.periodDaysHelp")} /></div></SectionCard><PayrollHero icon={<Landmark />} value={won.format(severance.severance)} label={severance.eligible ? t("payroll.severanceEligible", { average: won.format(severance.averageDailyWage), days: severance.serviceDays }) : t("payroll.severanceIneligible")} /></>}
    <div className="standard-notice"><ShieldCheck size={20} /><p><strong>{t("payroll.standard", { date: PAYROLL_STANDARD.effectiveDate })}</strong><span>{t("payroll.rates", { pension: PAYROLL_STANDARD.pensionEmployeeRate * 100, health: PAYROLL_STANDARD.healthEmployeeRate * 100, care: PAYROLL_STANDARD.longTermCareToHealthRate * 100, employment: PAYROLL_STANDARD.employmentEmployeeRate * 100 })}</span></p></div>
    <nav className="official-source-links" aria-label={t("payroll.sourcesLabel")}><a href="https://www.nps.or.kr/pnsinfo/ntpsklg/getOHAF0038M0.do?menuId=MN24001113&tab=tab5" target="_blank" rel="noreferrer">{t("payroll.pensionSource")}</a><a href="https://edi.nhis.or.kr/portal/images/popup/20251204_pop01longdesc.html" target="_blank" rel="noreferrer">{t("payroll.healthSource")}</a><a href="https://mob.tbht.hometax.go.kr/jsonAction.do?actionId=UTBSFAAM06F001" target="_blank" rel="noreferrer">{t("payroll.taxSource")}</a></nav>
    <ToolGuide title={t("payroll.guide.title")} description={t("payroll.guide.description")} blocks={(t("payroll.guide.blocks", { returnObjects: true }) as Array<{title:string;text:string}>).map((item) => ({ title: item.title, paragraphs: [item.text] }))} faq={(t("payroll.guide.faq", { returnObjects: true }) as Array<{q:string;a:string}>).map((item) => ({ question: item.q, answer: item.a }))} />
  </div>;
}

function NumberInput({ label, value, onChange, suffix, help }: { label: string; value: number; onChange: (value: number) => void; suffix: string; help?: string }) { return <label><span>{label}</span><div className="number-suffix"><input type="number" min={0} value={value} onChange={(event) => onChange(Math.max(0, Number(event.target.value)))} /><b>{suffix}</b></div>{help && <small>{help}</small>}</label>; }
function PayrollHero({ icon, value, label }: { icon: React.ReactNode; value: string; label: string }) { return <div className="payroll-hero">{icon}<div><strong>{value}</strong><p>{label}</p></div></div>; }
function Row({ label, value, formatter, total = false }: { label: string; value: number; formatter: Intl.NumberFormat; total?: boolean }) { return <div className={total ? "total" : ""}><dt>{label}</dt><dd>{formatter.format(value)}</dd></div>; }
