import { ArrowRightLeft, Copy, Download, FileJson, Table2 } from "lucide-react";
import { useEffect, useRef, useState } from "react";

import { PageHeader, PrimaryButton, SectionCard } from "../../components/ui";
import { ToolGuide } from "../../components/ToolGuide";
type Kind = "csv" | "json" | "html";
export function DataConverterPage() {
  const [source, setSource] = useState<Kind>("csv"); const [target, setTarget] = useState<Kind>("json"); const [input, setInput] = useState(""); const [output, setOutput] = useState(""); const [summary, setSummary] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const workerRef = useRef<Worker | undefined>(undefined);
  useEffect(() => () => workerRef.current?.terminate(), []);
  const convert = () => { workerRef.current?.terminate(); setBusy(true); setError(""); const worker = new Worker(new URL("./data-converter.worker.ts", import.meta.url), { type: "module" }); workerRef.current = worker; worker.onmessage = (event) => { setBusy(false); if (event.data.type === "error") setError(event.data.message); else { setOutput(event.data.result); setSummary(`${event.data.rows.toLocaleString()}행 × ${event.data.columns.toLocaleString()}열`); } worker.terminate(); if (workerRef.current === worker) workerRef.current = undefined; }; worker.postMessage({ source, target, text: input }); };
  const download = () => { const mime = target === "json" ? "application/json" : target === "html" ? "text/html" : "text/csv"; const url = URL.createObjectURL(new Blob([target === "csv" ? `\uFEFF${output}` : output], { type: `${mime};charset=utf-8` })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `worklazy-table.${target}`; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 0); };
  return <div className="page tool-page page-enter utility-page data-converter-page"><PageHeader eyebrow="DATA CONVERTER" title="CSV·JSON·HTML 표 변환" description="표 형태 데이터를 CSV, JSON 객체 배열 또는 HTML 표(table)로 서로 변환하세요." /><SectionCard title="변환 형식"><div className="converter-route"><FormatSelect label="입력" value={source} onChange={(value) => { setSource(value); if (value === target) setTarget(value === "csv" ? "json" : "csv"); }} /><ArrowRightLeft size={22} /><FormatSelect label="출력" value={target} onChange={setTarget} /></div><label className="file-control converter-file"><span>텍스트 파일 불러오기</span><input type="file" accept=".csv,.json,.html,.htm,text/csv,application/json,text/html" onChange={(event) => { const file = event.target.files?.[0]; if (file) void file.text().then(setInput); }} /></label></SectionCard><div className="utility-editor-grid"><SectionCard title="입력" description={`${input.length.toLocaleString()}자`}><textarea className="utility-textarea code-textarea" value={input} onChange={(event) => setInput(event.target.value)} placeholder="첫 행에 열 이름이 있는 CSV 또는 JSON 배열, HTML 표(table)를 입력하세요." /><div className="utility-inline-actions utility-inline-actions-spacer" aria-hidden="true" /></SectionCard><SectionCard title="결과" description={error || summary}><textarea className={`utility-textarea code-textarea${error ? " has-error" : ""}`} readOnly value={error || output} /><div className="utility-inline-actions"><button className="secondary-button" type="button" disabled={!output || Boolean(error)} onClick={() => void navigator.clipboard.writeText(output)}><Copy size={16} /> 복사</button><button className="secondary-button" type="button" disabled={!output || Boolean(error)} onClick={download}><Download size={16} /> 파일 저장</button></div></SectionCard></div><PrimaryButton accent="green" disabled={!input || source === target} loading={busy} onClick={convert}><Table2 size={18} /> 표 데이터 변환</PrimaryButton><ToolGuide title="표 데이터 변환 안내" description="파일과 텍스트는 브라우저의 별도 작업 공간에서 처리합니다." blocks={[{ title: "CSV", paragraphs: ["첫 행을 열 이름으로 사용하며 따옴표, 쉼표와 줄바꿈이 포함된 셀은 표준 CSV 따옴표 규칙으로 해석합니다."] }, { title: "JSON·HTML", paragraphs: ["JSON 객체 배열의 모든 키를 열로 모으고 HTML 표는 첫 번째 행을 머리글로 사용합니다."] }]} faq={[{ question: "대용량 CSV도 되나요?", answer: "브라우저 메모리 한도 안에서 별도 작업으로 처리합니다. 수십만 행은 파일 크기와 기기 메모리에 따라 시간이 걸릴 수 있습니다." }, { question: "HTML 안의 스크립트도 실행되나요?", answer: "아니요. 표 셀의 텍스트만 추출하며 입력 HTML을 화면에 삽입하거나 실행하지 않습니다." }]} /></div>;
}
function FormatSelect({ label, value, onChange }: { label: string; value: Kind; onChange: (value: Kind) => void }) { return <label><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value as Kind)}><option value="csv">CSV</option><option value="json">JSON</option><option value="html">HTML 표(table)</option></select>{value === "json" ? <FileJson size={18} /> : <Table2 size={18} />}</label>; }
