import { Copy, Download, ImagePlus, QrCode, ScanLine } from "lucide-react";
import QRCode from "qrcode";
import { useEffect, useRef, useState } from "react";

import { FileDropZone, PageHeader, PrimaryButton, SectionCard, SegmentedControl } from "../../components/ui";
import { ToolGuide } from "../../components/ToolGuide";

export function QrStudioPage() {
  const [mode, setMode] = useState<"create" | "scan">("create"); const [text, setText] = useState("https://worklazy.net/"); const [size, setSize] = useState(640); const [dark, setDark] = useState("#111118"); const [logo, setLogo] = useState<File>();
  const [scanFiles, setScanFiles] = useState<File[]>([]); const [scanned, setScanned] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const canvasRef = useRef<HTMLCanvasElement>(null); const workerRef = useRef<Worker | undefined>(undefined);
  useEffect(() => () => workerRef.current?.terminate(), []);
  useEffect(() => { void drawQr(canvasRef.current, text, size, dark, logo).catch((reason) => setError(reason instanceof Error ? reason.message : "QR 코드를 만들지 못했습니다.")); }, [text, size, dark, logo]);
  const download = () => canvasRef.current?.toBlob((blob) => { if (!blob) return; const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "worklazy-qr.png"; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 0); }, "image/png");
  const scan = async () => { const file = scanFiles[0]; if (!file) return; workerRef.current?.terminate(); setBusy(true); setError(""); setScanned(""); const worker = new Worker(new URL("./qr-scan.worker.ts", import.meta.url), { type: "module" }); workerRef.current = worker; worker.onmessage = (event) => { setBusy(false); if (event.data.type === "error") setError(event.data.message); else if (!event.data.data) setError("사진에서 QR 코드를 찾지 못했습니다."); else setScanned(event.data.data); worker.terminate(); if (workerRef.current === worker) workerRef.current = undefined; }; const buffer = await file.arrayBuffer(); worker.postMessage({ buffer, type: file.type }, [buffer]); };
  return <div className="page tool-page page-enter utility-page qr-page"><PageHeader eyebrow="QR STUDIO" title="QR 코드 생성·스캔" description="텍스트와 URL을 로고가 포함된 QR 코드로 만들거나 사진 속 QR 데이터를 브라우저에서 읽으세요." /><div className="mode-switch"><SegmentedControl value={mode} onChange={setMode} label="QR 기능" options={[{ value: "create", label: "QR 생성" }, { value: "scan", label: "사진 스캔" }]} /></div>
    {mode === "create" ? <div className="qr-layout"><SectionCard title="내용과 스타일"><label className="block-field"><span>URL 또는 텍스트</span><textarea value={text} onChange={(event) => setText(event.target.value)} /></label><div className="utility-form-grid"><label><span>크기</span><select value={size} onChange={(event) => setSize(Number(event.target.value))}><option value={320}>320px</option><option value={640}>640px</option><option value={1024}>1024px</option></select></label><label><span>QR 색상</span><input type="color" value={dark} onChange={(event) => setDark(event.target.value)} /></label><label className="span-2 file-control"><span>중앙 로고(선택)</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => setLogo(event.target.files?.[0])} /></label></div></SectionCard><SectionCard title="미리보기"><div className="qr-preview"><canvas ref={canvasRef} /></div><PrimaryButton accent="blue" disabled={!text} onClick={download}><Download size={18} /> PNG 다운로드</PrimaryButton></SectionCard></div> : <><SectionCard title="QR 사진 선택"><FileDropZone files={scanFiles} onFiles={(files) => setScanFiles(files.slice(-1))} accept="image/*" hint="QR 코드가 선명하게 보이는 이미지" accent="blue" /><div className="section-actions"><PrimaryButton accent="blue" disabled={!scanFiles.length} loading={busy} onClick={() => void scan()}><ScanLine size={18} /> QR 데이터 읽기</PrimaryButton></div></SectionCard>{(scanned || error) && <SectionCard title="스캔 결과"><div className={`scan-result${error ? " error" : ""}`}><QrCode size={21} /><p>{error || scanned}</p>{scanned && <button type="button" onClick={() => void navigator.clipboard.writeText(scanned)}><Copy size={17} /></button>}</div></SectionCard>}</>}
    <div className="format-capabilities"><span><QrCode size={17} /> 오류 복원 H</span><span><ImagePlus size={17} /> 중앙 로고</span><span><ScanLine size={17} /> 로컬 이미지 스캔</span></div><ToolGuide title="QR 코드 사용 안내" description="생성 내용과 스캔 이미지는 외부 서버에 전송되지 않습니다." blocks={[{ title: "중앙 로고", paragraphs: ["높은 오류 복원 수준을 사용하고 로고 뒤에 흰 여백을 넣습니다. 로고가 너무 복잡하면 일부 카메라에서 인식률이 떨어질 수 있습니다."] }, { title: "스캔", paragraphs: ["큰 이미지는 Worker에서 최대 2200px로 축소한 뒤 명암 반전을 포함해 분석합니다."] }]} faq={[{ question: "QR URL의 안전성도 검사하나요?", answer: "아니요. QR 데이터를 표시할 뿐 연결된 사이트의 안전성을 보증하지 않습니다." }, { question: "카메라 실시간 스캔도 되나요?", answer: "현재는 개인정보 권한을 최소화하기 위해 업로드한 사진 스캔만 지원합니다." }]} /></div>;
}

async function drawQr(canvas: HTMLCanvasElement | null, text: string, size: number, dark: string, logo?: File) { if (!canvas || !text) return; await QRCode.toCanvas(canvas, text, { width: size, margin: 3, errorCorrectionLevel: "H", color: { dark, light: "#ffffff" } }); if (!logo) return; const url = URL.createObjectURL(logo); try { const image = await loadImage(url); const context = canvas.getContext("2d"); if (!context) return; const box = size * 0.22; const x = (size - box) / 2; const y = x; context.fillStyle = "white"; context.beginPath(); context.roundRect(x - 8, y - 8, box + 16, box + 16, size * 0.025); context.fill(); context.drawImage(image, x, y, box, box); } finally { URL.revokeObjectURL(url); } }
function loadImage(url: string) { return new Promise<HTMLImageElement>((resolve, reject) => { const image = new Image(); image.onload = () => resolve(image); image.onerror = () => reject(new Error("로고 이미지를 읽지 못했습니다.")); image.src = url; }); }
